#!/usr/bin/env bash
# Installs and sets up dev environment for ngnix

apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
# sed -i "s/listen [0-9]* default_server;/listen 80 default_server;/g" /etc/nginx/sites-available/default
# sed -i "s/listen \[.*\].[0-9]* default_server;/listen [::]:80 default_server;/g" /etc/nginx/sites-available/default
if [ "$(pgrep -x 'nginx' | wc -l)" -ge 1 ]
then
    service nginx restart
else
    service nginx start
fi
