#!/usr/bin/env bash
# Installs and sets up dev environment for ngnix

apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
SERVER_CONFIG=\
"server {
	listen 80 default_server;
  	listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;
	server_name _;
        location / {
                try_files \$uri \$uri/ =404;
	}
        rewrite ^/redirect_me$ http://www.youtube.com/ permanent;
}"

echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ]
then
    service nginx restart
else
    service nginx start
fi
