#!/usr/bin/env bash
# Script changes the address localhost resolves to

cp /etc/hosts ~/hosts.new
sed -i 's/^127\.0\.0\.1\tlocalhost$/127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
