#!/usr/bin/env bash
# changes the user running nginx from superuser(root) to nginx
sudo sed -i "s/\([ :]\)80 /\18080 /" /etc/nginx/sites-enabled/default
sudo pkill apache2
sudo chown -R nginx:nginx /etc/nginx/
sudo chmod u+rw /etc/nginx/nginx.conf
sudo -u nginx service nginx start
